### ISSUE TITLE
Resource search improvements

### ISSUE THREAD

**Issue by FelixLoether** [City-of-Helsinki/huvaja#102]
- [x] Hover effect to resource row. #104 
- [x] Sticky time row. #99
- [x] Time row should not be sticky on resource page. #105
- [x] Show current time (vertical line). #98
- [x] Search criteria. #108 
- [x] Time filters #121
  - Move date filter from SearchControls to DateSelector
  - Add date time range filter ("Vapaana aikavälille")
  - Changing date time range filter should change date filter (use start date) but not the other way around
- [x] Automatic search (without button click).
