### ISSUE TITLE
Improve making reservations

### ISSUE THREAD

**Issue by FelixLoether** [City-of-Helsinki/huvaja#111]
- [x] Back button #95
- [x] Improve top of the page #95
- [x] Fields for start and end dates and times #114
- Check overlaps when making reservation. EDIT: don't do yet.
- [x] Field for more information #112
