### ISSUE TITLE
Catering orders with API

### ISSUE THREAD

**Issue by evehmane** [City-of-Helsinki/huvaja#169]
Issues:
- [x] Use the price page URL from the API. #231
- [x] Show catering products based on API data. #234
- [x] Save catering orders to API. #242
- [x] Show catering orders from API. #243
- [ ] Editing/deleting catering orders. #211 
- [x] Misc. fixes
  - Change button order of catering modal so that "Save" is on the right.
  - Maybe change button name from "Tallenna tilaus" to for example "Valmis" so it's clear that clicking the button in catering modal doesn't yet save the catering order.

Problems:
- When editing a reservation with a catering order, what happens when changing to a resource that has no catering provider? #252

---

Todo:
- [ ] Get price page URL from API
- [ ] Get products (with categories) from API. Currently they are hardcoded. "Ateriakokonaisuudet" should be the last category on the list because it's used rarely. Suggest to backend developers that the order would be decided in backend.
- [ ] After reservation has been posted successfully, make another request to add catering orders
- [ ] Updating catering orders (this could be a separate issue)
- [ ] Change button order of catering modal so that "Save" is on the right.
- [ ] If creating/updating catering order fails, show  #message.

When initializing app:
- GET /catering_provider
- GET /catering_product_category
- GET /catering_product

When showing reservation modal / editing reservation:
- GET /catering_order?reservation=123 (The filter not yet implemented in backend but will be soon)

Create/edit/delete:
- POST /catering_order
- PUT /catering_order/234
- DELETE /catering_order/234

Example POST/PUT/GET data:
```
{
  "reservation": 532,
  "order_lines": [
      {
        "product": 1,
          "quantity": 7
        
    }
  ],
  "invoicing_data": "1234",
  "message": "piupau"
}
```
